# This file is covered by the LICENSE file in the root of this project.
name: "kitti"
labels: 
  0 : "non-snow"
  1 : "snow"
  9 : "unlabelled"

color_map: # bgr
  0 : [50, 200, 0]      # non-snow
  1 : [255, 255, 255]  # snow
  9 : [0, 0, 0]

content: # as a ratio with the total number of points
  0: 0.90
  1: 0.10 # true 0.03
  9: 0.0

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  9 : 0     # unlabeled
  0 : 1     # non-snow
  1 : 2     # snow

learning_map_inv: # inverse of previous map
  0: 9      # unlabeled
  1: 0      # non-snow
  2: 1      # snow

learning_ignore: # Ignore classes
  0: True      # unlabeled
  1: False     # non-snow
  2: False     # snow

split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
#    - 8
#    - 9
    - 10
  valid:
    - 8
    - 9
  test:
#    - 11
#    - 12
#    - 13
#    - 14
#    - 15
#    - 16
#    - 17
#    - 18
#    - 19
#    - 20
#    - 21
    - 22
